name: CI
on:
  push:
jobs:
  lint_and_test:
    runs-on: ubuntu-22.04
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: frere
    env:
      DATABASE_URL: mysql://root:secret@localhost:3306/frere
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v3
        with:
          path: |
            node_modules
            server/node_modules
            web/node_modules
          key: ${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - run: yarn install
      - run: yarn prisma generate
      - run: yarn run lint
      - run: yarn prisma migrate deploy
      - run: yarn run test
